name: trendz_customer
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

flutter_launcher_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "lib/assets/images/logo.png"
  image_path_ios: "lib/assets/images/logo.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "lib/assets/images/sky.jpg" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "lib/assets/images/sky.jpg" # only available for Android 8.0 devices and above
  adaptive_icon_foreground_inset: 16 # only available for Android 8.0 devices and above
  adaptive_icon_monochrome: "lib/assets/images/sky.jpg" # only available for Android 13 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  web:
    generate: true
    image_path: "lib/assets/images/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "lib/assets/images/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "lib/assets/images/logo.png"

version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  intl_phone_field: ^3.2.0
  provider: ^6.1.2
  dio: ^5.7.0
  iconsax: ^0.0.8
  google_sign_in: ^6.2.2
  flutter_facebook_auth: ^7.1.1
  shared_preferences: ^2.3.3
  flutter_launcher_icons: ^0.14.2
  android_intent_plus: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/images/



